repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ".*(.fits|.fts|.fit|.txt)$"
      - id: check-yaml
      - id: debug-statements
      - id: check-added-large-files
      - id: end-of-file-fixer
        exclude: ".*(.fits|.fts|.fit|.txt|tca.*)$"
      - id: mixed-line-ending
        exclude: ".*(.fits|.fts|.fit|.txt|tca.*)$"
ci:
  autofix_prs: false
