repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: debug-statements
      - id: check-added-large-files
ci:
  autofix_prs: false
