# This workflow generates web output
name: asv-gh-pages

on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  asv-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results repo
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install asv virtualenv
          
      - name: Publish results
        run : asv gh-pages
