name: Deploy to Github Pages

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  asv-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install asv virtualenv
      - name: Git config
        run : |
          git config --global user.email " "
          git config --global user.name "GitHub Actions"
      - name: Pull new commits from sunpy-benchmarks repo
        run : |
          git checkout gh-pages
          git pull
          git checkout main
      - name: Publish results
        run : asv gh-pages
